// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYHfVxfv1bVFtfcJm7uRbTKJTm-voGP98',
    appId: '1:196308226619:web:574736d5834a71df4d021e',
    messagingSenderId: '196308226619',
    projectId: 'news-app-9e3d7',
    authDomain: 'news-app-9e3d7.firebaseapp.com',
    storageBucket: 'news-app-9e3d7.firebasestorage.app',
    measurementId: 'G-SM7M5M3RXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrKVSYJikD9nGae3WmjbBXRZIeJb9uD4',
    appId: '1:196308226619:android:aa7dfe3a0750627c4d021e',
    messagingSenderId: '196308226619',
    projectId: 'news-app-9e3d7',
    storageBucket: 'news-app-9e3d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisN1DfdUp6uBxXfjxXLp_wfsRtCQNJQo',
    appId: '1:196308226619:ios:2046d48b8378d60d4d021e',
    messagingSenderId: '196308226619',
    projectId: 'news-app-9e3d7',
    storageBucket: 'news-app-9e3d7.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDisN1DfdUp6uBxXfjxXLp_wfsRtCQNJQo',
    appId: '1:196308226619:ios:2046d48b8378d60d4d021e',
    messagingSenderId: '196308226619',
    projectId: 'news-app-9e3d7',
    storageBucket: 'news-app-9e3d7.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYHfVxfv1bVFtfcJm7uRbTKJTm-voGP98',
    appId: '1:196308226619:web:fe86f8a7ba13baf24d021e',
    messagingSenderId: '196308226619',
    projectId: 'news-app-9e3d7',
    authDomain: 'news-app-9e3d7.firebaseapp.com',
    storageBucket: 'news-app-9e3d7.firebasestorage.app',
    measurementId: 'G-TCXP8V26TC',
  );

}